apiVersion: v1
kind: Service
metadata:
  name: obk-controller-svc
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 3882
      targetPort: 3882
  selector:
    app: obk-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-obk-controller
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
        # enable access to the console SPA (the front)
        - path: /obk-console
          pathType: Prefix
          backend:
            service:
              name: obk-controller-svc
              port:
                number: 3882
        # enable access to the console authorizator API
        - path: /obk-authorizator/obk-console-authorizator
          pathType: Prefix
          backend:
            service:
              name: obk-authorizator-obk-console-authorizator-svc
              port:
                number: 3882
---
apiVersion: jfvilas.at.outlook.com/v1
kind: ObkAuthorizator
metadata:
  name: obk-console-authorizator
  namespace: default
spec:
  config:
    replicas: 1
    prometheus: false
    api: true
    logLevel: 9
  ingress:
    name: ingress-obk-controller
    provider: ingress-nginx
    class: nginx
  validators:
    - basicAuth:
        name: obkconsole
        realm: ObkControllerConsole
        storeType: inline
        users: 
          - name: admin
            password: admin
  rulesets:
    - name: general
      uriPrefix: [ '/obk-authorizator' ]
      rules:
        - uris: [ '' ]
          uritype: prefix
          type: unrestricted
    - name: obkconsole-unprotected
      uriPrefix: [ '/obk-console' ]
      rules: 
        - uris: [ '' ]
          uritype: prefix
          type: unrestricted
